### ISSUE TITLE
Chat UI

### ISSUE THREAD

**Issue by miguel-pd95** [TextRoulette/Frontend#3]
This is the main view where the users can chat with whoever they got linked to and see the data in the side view.

**Comment by miguel-pd95** [comment]
This is the main view

**Comment by miguel-pd95** [comment]
Falta agregar más datos de los usuarios en la vista lateral.
Idioma - Edad - Género - País

**Comment by chrismir1320** [comment]
Tiene problemas desplegando los mensajes y de quién son, así que hay arreglarlo.

**Comment by miguel-pd95** [comment]
Bug fixed! :D

Pero creo que encontré otro... (no le digan al profe)
